### ISSUE TITLE
jTessBoxEditor crashes when  eng.traineddata is not given

### ISSUE THREAD

**Issue by srdg** [nguyenq/jTessBoxEditor#11]
+ Environment : Ubuntu 16.04 LTS
+ Tesseract : 4.0.0-beta.1-376-gb1f79
+ openjdk version "1.8.0_171"
+ OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
+ OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

I am trying to create box files for images using jTessBoxEditor. It requires me to explicitly specify the language along with giving the path to tesseract executable and the training data.  I gave it a custom language which consisted only of digits, but the outputs came in form of digits, _alphabets_ and even _special characters!_ 
I removed the `eng.traineddata` file from my tessdata directory, and jTessBoxEditor wouldn't even start to read the images. I get the following error log :

```
** Make Box Files **
[/home/soumik/local/bin/tesseract, img.f158.exp0.png, img.f158.exp0, batch.nochop, makebox]
Error opening data file /usr/local/share/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.

```

**Comment by srdg** [comment]
@nguyenq I had my custom traineddata with which I intended to train Tesseract. I have trained tesseract via command line through the same. Does jTessBoxEditor train tesseract only using `eng.traineddata`?

**Comment by nguyenq** [comment]
If Bootstrap Language option is not specified, then `eng` is used. You certainly can specify your custom lang as the bootstrap language.

**Comment by srdg** [comment]
@nguyenq okay, got it. Closing the issue.
