### ISSUE TITLE
Unable insert a box if there is not any box #7

### ISSUE THREAD

**Issue by Ninjahaha** [nguyenq/jTessBoxEditor#15]
nguyenq say can insert a line into that empty box and adjust it accordingly in the editor
:A 0 0 10 15 0
--
But how to insert to box data?there unable to edit?

**Comment by Ninjahaha** [comment]
https://github.com/nguyenq/jTessBoxEditor/issues/7

**Comment by nguyenq** [comment]
You can open the empty box file in a text editor, add the line, and save it. Then open it in jTessBoxEditor.

**Comment by Ninjahaha** [comment]
don't know where line start to add?I have 299 pic

**Comment by nguyenq** [comment]
You select an existing box and then click Insert button -- a new box will be inserted after the currently selected box.

**Comment by nguyenq** [comment]
Fixed in commit https://github.com/nguyenq/jTessBoxEditor/commit/4ae13904b6e6116b42efeff1b4a5fdb14296c193.
