### ISSUE TITLE
Program "opening" but unable to bring it to focus.

### ISSUE THREAD

**Issue by empdarkness** [nguyenq/jTessBoxEditor#16]
I've had both times where it has worked and hasnt. I am currently running Windows 10 v2004.
The software does technically open, however i cannot see the window of it, nor can i bring it to focus, through clicking or alt+tab.

**Comment by nguyenq** [comment]
It sounds like it failed to lauch. Does it happen to both Swing and FX versions? What's the version of Java you have?

**Comment by empdarkness** [comment]
Unsure what you mean by Swing and FX versions. (Using jTessBoxEditor-2.3.0.zip if thats any help)
Java version is 1.8.0_251-b08

**Comment by nguyenq** [comment]
There's also a jTessBoxEditorFX, which employs JavaFX UI Framework.

Can you lauch from the command line to see if there is any error print out?

**Comment by empdarkness** [comment]
No error gets spit out. I also just noticed that there was an FX and non FX version. Works consistently on non-FX.

**Comment by nguyenq** [comment]
So the ticket was filed against the wrong project. Let me see if I could try to reproduce the error with the FX-version program launching; it was working with JDK 1.8.
