### ISSUE TITLE
"Reload" action does not reload box file succefully

### ISSUE THREAD

**Issue by hereis00** [nguyenq/jTessBoxEditor#18]
As what the title says, After hitting "Reload", nothing changed.

**Comment by hereis00** [comment]
Hitting "open" current file also changes nothing.

**Comment by nguyenq** [comment]
Unable to reproduce the report issues. Reload would discard any change made since last saved or opened.

**Comment by hereis00** [comment]
@nguyenq 1. Run "Make Box File." 2. Load box and modify some boxes arbitrarily and "Save" it. 3. Redo" Make Box File". 4. Hit Reload to reload box info, but it didn't turn back to the original state, the one before i modifed it.
Or: 4. Execute "Open" action, also no changes.
Windows 10, jTessBoxEditor v2.3.1, JRE 8u251.

**Comment by nguyenq** [comment]
That sequence of actions is a little unusual. Reload would work if changes were made using Box Editor panel's editing function; it would not work if changes were made to the underlying box file.

If you open the file again, it should work.

**Comment by hereis00** [comment]
@nguyenq It's good to me that "Open" action does the right thing now.
Now i know how to reach my expectation: 1. Make box -> 2. modify and Save -> 3. Make box -> 4. Modify and do not Save -> 5. Reload, and it resets successfully. This means there is something wrong with "Reload" action, it could do better, Reload box correctly without step 4, if it was fixed up.

**Comment by nguyenq** [comment]
Each tab represents a different function, independent of each other. You can consider Reload as Undo operation as it discards all changes made to the boxes by editing actions in Box Editor tab.

When you make box again, you will be warned about overwriting existing box files. If you want to retain any change to the box files, you need to move them out of that folder.

**Comment by hereis00** [comment]
@nguyenq Got it! Thanks for your time and this great tool.
