### ISSUE TITLE
Compile instructions in README.md

### ISSUE THREAD

**Issue by tofutim** [nguyenq/jTessBoxEditor#2]
It would be nice to have compile instructions in the README.md. I don't think I have compiled java for about 15 years! :)

**Comment by tofutim** [comment]
I figured out that I needed 'ant' (besides javac) and now get the following
```
    [javac] 
...\jTessBoxEditor\test\net\sourceforge\tessboxeditor\GuiWithTrainerTest.java:3: error: package org
.junit does not exist
```
I presume I need to install org.junit somewhere.

**Comment by tofutim** [comment]
Or maybe I should be using eclipse?

**Comment by tofutim** [comment]
I tried adding junit-4.12.jar and hamcrest-core-1.3.jar to the lib directory and running 'ant' again, but this did not work.

**Comment by tofutim** [comment]
ok maybe I need netbeans

**Comment by nguyenq** [comment]
The project is NetBeans-based. NB 8.1 has all the necessary libraries to compile the project.

**Comment by tofutim** [comment]
yes, i finally figured that out, thanks!

any chance of going to tesseract 3.04?

**Comment by nguyenq** [comment]
`tesseract.exe` of 3.04 can now be built, but other training executable for Windows are not yet available. Someone will need to build them.

**Comment by tofutim** [comment]
before I go off the deep end doing this, do you know where i can get the 3.02 langdata? I can seem to find it anywhere and need to train some Chinese.

**Comment by nguyenq** [comment]
It's still at old Google site: https://code.google.com/p/tesseract-ocr/downloads/list

**Comment by tofutim** [comment]
thanks, i took a look but could only find traineddata - do you know where I get the raw ingredients (frequency_list, etc.)

**Comment by nguyenq** [comment]
You may want to check the `langdata` repository:

https://code.google.com/p/tesseract-ocr/source/browse/?repo=langdata

**Comment by tofutim** [comment]
When I open then chinese langdata it just is the traineddata - but maybe
 that is all there is?

**Comment by nguyenq** [comment]
Update relevant links:

https://github.com/tesseract-ocr
https://sourceforge.net/projects/tesseract-ocr-alt
