### ISSUE TITLE
Làm sao train đồng thời các loại box ?

### ISSUE THREAD

**Issue by Vance-ng-vn** [nguyenq/jTessBoxEditor#26]
Mình mới biết đến tesseract thôi, đang tính train thử một số font scratch từ các bộ phim, anime; nhưng mà thấy hơi khó sử dụng, các tài liệu trên mạng cũng ít và khó hiểu!

Cơ bản mình hiểu là có 3 loại box:
- Standard Box: Cái này để train thêm font mới, nhưng không biết việc lặp lại của các ký tự có được không, vì ảnh scratch nên trông không mượt như font ttf được!
- LSTM Box: Đây là box về sự tương quan giữa các từ, các chữ với nhau.
- WordStr Box: Không rõ lắm, nhưng có thể là các từ đơn lẻ.

Để tạo nên một model thì chắc phải train cả 3 đúng không nhỉ ? nhưng jtessbox chỉ tạo một lần file.box nên cũng chả hiểu là như nào!

Có thử qua project TessTrain, cũng rất khó để hiểu nó hoạt động, theo Readme.md thì chỉ cần tạo LSTM box + hình ảnh(.png, .tiff) là train được, nhưng như vậy thì lại thiếu dữ liệu các ký tự, không biết là liệu nó hoạt động hay không... ?

**Comment by nguyenq** [comment]
Standard box dùng trong training Tesseract 3, là phiên bản mà jTessBoxEditor hỗ trợ.

LSTM Box và WordStr Box được dùng trong phiên bản 4 và 5 -- bạn hãy tham khảo trang [Training for Tesseract 5](https://tesseract-ocr.github.io/tessdoc/#training-for-tesseract-5). Training cho bản đó quy trình khá phức tạp, ngay tôi cũng chưa từng thử qua, nhưng nhiều developers khác đã gặt hái được thành công. Bạn hãy đọc những post trong https://groups.google.com/g/tesseract-ocr để biết thêm.
