### ISSUE TITLE
[Feature]support to draw a area to add box, zoom image

### ISSUE THREAD

**Issue by EasyEDA2021** [nguyenq/jTessBoxEditor#27]
at present, add a new box must modify the location and width and height, it is hard to add for multiple text box image
1, suggest support to use mouse to draw a area box to add the box, just like this
https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/PPOCRLabel/data/gif/kie.gif

2. suggest support zoom in and zoom out image, will be good for small images

thank you for your greate job for jTessBoxEditor, it is a very nice tool
hope you have a good day!

**Comment by nguyenq** [comment]
The box editor was designed to allow simple edit or correction of box files. Adding a large number of new boxes is not within the scope of the design.

The Box View tab offers a blown-up view of the currently selected box to facilitate various box adjustments.

Anyway, as the tool is not going to support the new training method introduced in Tesseract 4, no new features will be planned as the software has entered its maintenance phase.

Thanks.
