### ISSUE TITLE
So hard to use...

### ISSUE THREAD

**Issue by ChairmanMawh** [nguyenq/jTessBoxEditor#28]
This tool would be a lot easier to use if it had some keyboard handling for the box editor, for example:

Click a box
It goes red
**I should be able to use the cursor keys to move it around (left and right change X, up and down change Y)**
**I should be able to press SHIFT+cursor key to make the box wider and narrower, taller and shorter (shift+left decreases W, shift + right increases W, shift + up decreases H, shift+down increases H)**
**I should be able to type a character while the box is highlighted, to set the Char column for the highlighted box, to that character**

My feature requests are in bold.. :)

Perhaps even we could have drag-and-drop with the mouse to resize the boxes, mouse wheel zoom in and out.. Mayb it would be easier to implement large crosshairs and we click the top-left and then bottom-right points to reshape the box

**Comment by nguyenq** [comment]
Accessibility is a feature built into the program. If you read Help page, you'll see:

The following hotkeys are available in Box View for ease of editing:

W/S - move box up/down; A/D - move box left/right
Q/E - decrease/increase box width; R/F - decrease/increase box height
</> - previous/next box
X - edit character in box

**Comment by nguyenq** [comment]
@ChairmanMawh Can this ticket be closed?
