### ISSUE TITLE
Arabic character popup

### ISSUE THREAD

**Issue by bluemix** [nguyenq/jTessBoxEditor#4]
Hello dear,
I have this problem when I peek into a character

<img width="556" alt="screen shot 2017-02-14 at 00 32 16" src="https://cloud.githubusercontent.com/assets/3332274/22904344/28b322e8-f24d-11e6-9321-4ac77f7f0d4b.png">

as you can see, the Arabic letter 'و' has artifacts on it when displayed.

I am really hoping to help you as much as I can with your program.
Thanks a lot for it 👍

**Comment by nguyenq** [comment]
Which program version displays this problem -- Swing or JavaFX? Can you attach a **small** sample to reproduce the issue? And we need more info about your system configuration -- OS, Java version, etc.

**Comment by bluemix** [comment]
Yes, sure.

<img width="513" alt="screen shot 2017-02-14 at 08 27 27" src="https://cloud.githubusercontent.com/assets/3332274/22916690/f6a3cc32-f290-11e6-8e4c-73ad0805dc1e.png">

Sample
[ara.semi-bahij.exp3.zip](https://github.com/nguyenq/jTessBoxEditor/files/773238/ara.semi-bahij.exp3.zip) = ara.semi-bahij.exp3.box + ara.semi-bahij.exp3.tiff

I am using 
macOS Sierra 10.12.3 (16D32)
Java 8 update 121 (build 1.8.0_121-b13)

**Comment by nguyenq** [comment]
It's probably a font issue on macOS as the tooltip displays properly on Windows and Linux Ubuntu.

**Comment by nguyenq** [comment]
Unable to reproduce on development machines.
