### ISSUE TITLE
train doesn't launch jTessBoxEditor on Ubuntu LTS 16.04.

### ISSUE THREAD

**Issue by renweizhukov** [nguyenq/jTessBoxEditor#6]
Unzip jTessBoxEditor 1.7.3 on Ubuntu LTS 16.04. When I use the train script to launch jTessBoxEditor, I hit the following error:

```bash
$ ./train
Error: Could not find or load main class jTessBoxEditor
```

If I change the java launch option from "-cp" to "-java", then I can successfully launch jTessBoxEditor, i.e., from
```bash
$JAVACMD -Xms128m -Xmx1024m -cp "$PROGDIR/$PROGRAM.jar" $PROGRAM $@
```
to
```bash
$JAVACMD -Xms128m -Xmx1024m -jar "$PROGDIR/$PROGRAM.jar" $PROGRAM $@
```

FYI, the java version on my machine is as below:

```bash
$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by nguyenq** [comment]
It used to work with older JVM. Have committed a fix: https://github.com/nguyenq/jTessBoxEditor/commit/c6891d83ffaed49f55fe41b81444abac8a156717

Thank you.

**Comment by renweizhukov** [comment]
Thank you for the quick fix.
