### ISSUE TITLE
could not insert a box if there is not any box

### ISSUE THREAD

**Issue by guoxiaod** [nguyenq/jTessBoxEditor#7]
could not insert a box if there is not any box in the "box coordinaties" page

**Comment by nguyenq** [comment]
It needs an existing box to insert the new box after.

**Comment by guoxiaod** [comment]
Sometimes tesseract can not recognize any characters, so we should manually insert the box in this case.

**Comment by nguyenq** [comment]
In that case, you can insert a line into that empty box and adjust it accordingly in the editor:

`A 0 0 10 15 0`

**Comment by Ninjahaha** [comment]
how to insert to box data?there unable to edit

**Comment by macky8** [comment]
for inserting empty box you need to add empty box file with 1 line of coordinates and label for example: X 91 76 169 191 0
This .box file need same name as .png or .tif file and have to be **in same folder**....for example test.box and test.png  **in same folder**
after that when you open test.png box appear and you have insert another
