### ISSUE TITLE
how could run it on Mac?

### ISSUE THREAD

**Issue by GitHubGS** [nguyenq/jTessBoxEditor#8]
dear, 
latest java jdk-9 installed already, mac system.
how could make the program run correctly on Mac?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I was used to use version1.5 in the windows platform, it has a jTessBoxEditor.jar file, just double click, then work well.

**Comment by nguyenq** [comment]
Last time we checked, it worked well with Java 9 on Windows 10. Did not have a chance to test on other OS. You encounter a problem on Mac?

**Comment by GitHubGS** [comment]
Using JAVA 8 instead, the problem was solved! anyway, many thanks for your reply!

**Comment by coidacis** [comment]
I have the problem of defining the dirs for tesseract executables and training data. I've prepared the box and tif files but the trainer gives me "error= 2 No such file or directory"
